In [1]:
import numpy as np 

In [2]:
vector = np.array([23,32])
print("Vector:", vector)

Vector: [23 32]


In [3]:
mat = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
a= np.array([1,2,3])
b= np.array([4,5,6])

In [5]:
print("Addition: ",np.add(a,b))
print("substraction: ",np.subtract(a,b))
print("Dot Product: ",np.dot(a,b))
print("cross Product: ",np.cross(a,b))
print("Multiply: ",np.multiply(a,b))

Addition:  [5 7 9]
substraction:  [-3 -3 -3]
Dot Product:  32
cross Product:  [-3  6 -3]
Multiply:  [ 4 10 18]
